//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string ProductCod { get; set; }
        public string ProductName { get; set; }
        public string Email { get; set; }
        public override string ToString()
        {
            return $"{Id,3} | {ProductCod, 3} | {ProductName, 50} | {Email,50}";
        }
    }
}
